#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a number: " n
case $n in
    ???) 
        echo "One";;
    2) 
        echo "Two";;
    aa) 
        echo "Three";;
    *.txt) 
        echo "Four";;
    *) 
        echo "Other";;
esac


read -p "Enter a value: " s
case $s in
    1|2) 
        echo "Number One or Two";;
    [3-9]) 
        echo "Number 3 through 9";;
    ??) 
        echo "Two characters";;
    *.js) 
        echo "*.js";;
    *) 
        echo "Other";;
esac
