#!/bin/bash

check_even () {
    # local variable within the function
    local mod=2
    echo "The value of mod is $mod"
    if [ $(("$1" % $mod)) -eq 0 ]
    then 
       echo "The number $1 is even!";
    else 
       echo "The number $1 is odd!"
    fi
    echo $2
}


number=2344
str='second parameter.'

check_even $number $str
echo $mod
